# BootStudio
#
# Boots Hecks for the Studio surface. Encapsulates the path-shape
# wiring : studio.bluebook + studio.hecksagon sit next to app.rb,
# but Hecks.boot expects them in a hecks/ subdir. We bridge by
# loading the bluebook/hecksagon directly and constructing a
# Runtime from the resulting domain IR.
#
# Falls back to Hecks.boot(dir) if a hecks/ subdir is detected
# (so the same code runs in both layouts).
#
# Also seeds six TickedFeature cadence rows after boot (heart,
# breath, ultradian, circadian, sleep_cycle, mindstream) so the
# dashboard's running-features grid is populated immediately
# instead of showing the empty-state alert.
#
# Usage :
#   runtime = BootStudio.call(__dir__)
#   runtime["TickedFeature"].all
#

require "hecks"
require "hecksagon"
require "hecksagon/loader"

module BootStudio
  # Default cadences seeded into TickedFeature on boot. Names
  # match the daemons retired in Phase 11 ; intervals are the
  # cadence's natural period in milliseconds.
  CADENCES = [
    { name: "heart",       expected_interval_ms: 1_000      },
    { name: "breath",      expected_interval_ms: 4_000      },
    { name: "ultradian",   expected_interval_ms: 5_400_000  },
    { name: "circadian",   expected_interval_ms: 86_400_000 },
    { name: "sleep_cycle", expected_interval_ms: 5_400_000  },
    { name: "mindstream",  expected_interval_ms: 8_000      }
  ].freeze

  module_function

  # Boot the studio. Returns a single Hecks::Runtime ready to serve.
  # Seeds the six default cadences as TickedFeature rows so /health
  # and the dashboard have content from the first request.
  #
  # @param dir [String] absolute path to the studio directory
  # @return [Hecks::Runtime]
  def call(dir)
    runtime = boot_runtime(dir)
    seed_cadences(runtime)
    runtime
  end

  # Underlying boot — picks between Hecks.boot (when a hecks/
  # subdir exists) and the flat-layout direct-load path.
  #
  # @param dir [String] absolute path to the studio directory
  # @return [Hecks::Runtime]
  def boot_runtime(dir)
    bluebook_paths = Dir[File.join(dir, "*.bluebook")].sort
    hecksagon_paths = Dir[File.join(dir, "*.hecksagon")].sort

    return Hecks.boot(dir) if bluebook_paths.empty? && File.directory?(File.join(dir, "hecks"))

    raise "BootStudio: no .bluebook found in #{dir}" if bluebook_paths.empty?

    hecksagon_paths.each { |p| Hecksagon::Loader.load(p) }

    domain = load_domain(bluebook_paths)
    Hecks.load(domain)
  end

  # Eval each .bluebook in the directory ; return the resulting
  # Hecks::BluebookModel::Structure::Domain (last one wins).
  def load_domain(bluebook_paths)
    domain = nil
    bluebook_paths.each do |path|
      Hecks.instance_variable_set(
        :@_inferred_bluebook_name,
        File.basename(path, ".bluebook").split("_").map(&:capitalize).join
      )
      Hecks::DSL::AggregateBuilder::VoTypeResolution.with_vo_constants do
        Kernel.load(path)
      end
      domain = Hecks.last_domain
    end
    domain
  end

  # Seed TickedFeature with the six default cadences. Each runs
  # CreateTickedFeature (auto-generated by the :crud capability) ;
  # status defaults to "pending" since no real Tick has landed yet.
  # Idempotent : skips a cadence whose name is already on file
  # (warm boots after .heki persistence will re-load existing rows).
  #
  # Best-effort : if the runtime didn't get a CreateTickedFeature
  # generator (crud disabled, etc.), seeding is silently skipped so
  # the studio still boots cleanly.
  def seed_cadences(runtime)
    repo = runtime["TickedFeature"]
    return unless repo&.respond_to?(:all)
    existing = Array(repo.all).map { |r| r.respond_to?(:name) ? r.name.to_s : r.to_s }.to_set

    CADENCES.each do |cadence|
      next if existing.include?(cadence[:name])
      runtime.run(
        "CreateTickedFeature",
        name:                 cadence[:name],
        expected_interval_ms: cadence[:expected_interval_ms],
        status:               "pending",
        last_tick_at:         nil
      )
    end
  rescue StandardError => e
    warn "[BootStudio] cadence seeding failed: #{e.class}: #{e.message}"
  end
end
